[package]
name = "simulatron-utils"
version = "2.0.0-beta"
authors = ["Chris Riches <chrisriches42@gmail.com>"]
edition = "2021"
description = "Reusable utilities for the Simulatron project"
repository = "https://github.com/cjriches/simulatron"
license = "MIT"
