[package]
name = "simulatron"
version = "0.1.0"
authors = ["Chris Riches <chrisriches42@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.4.2"
notify = "4.0.15"
web-view = "0.6.2"

[dev-dependencies]
rand = "0.7.3"
tempfile = "3.1.0"
